/*
 * Pricing Rules API
 *
 * The Pricing Rules API manages a pricing rules of items 
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CommonPricingRule struct for CommonPricingRule
type CommonPricingRule struct {
	Rule int32 `json:"rule"`
	Weight int32 `json:"weight"`
}

// NewCommonPricingRule instantiates a new CommonPricingRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonPricingRule(rule int32, weight int32, ) *CommonPricingRule {
	this := CommonPricingRule{}
	this.Rule = rule
	this.Weight = weight
	return &this
}

// NewCommonPricingRuleWithDefaults instantiates a new CommonPricingRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonPricingRuleWithDefaults() *CommonPricingRule {
	this := CommonPricingRule{}
	return &this
}

// GetRule returns the Rule field value
func (o *CommonPricingRule) GetRule() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.Rule
}

// GetRuleOk returns a tuple with the Rule field value
// and a boolean to check if the value has been set.
func (o *CommonPricingRule) GetRuleOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Rule, true
}

// SetRule sets field value
func (o *CommonPricingRule) SetRule(v int32) {
	o.Rule = v
}

// GetWeight returns the Weight field value
func (o *CommonPricingRule) GetWeight() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.Weight
}

// GetWeightOk returns a tuple with the Weight field value
// and a boolean to check if the value has been set.
func (o *CommonPricingRule) GetWeightOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Weight, true
}

// SetWeight sets field value
func (o *CommonPricingRule) SetWeight(v int32) {
	o.Weight = v
}

func (o CommonPricingRule) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["rule"] = o.Rule
	}
	if true {
		toSerialize["weight"] = o.Weight
	}
	return json.Marshal(toSerialize)
}

type NullableCommonPricingRule struct {
	value *CommonPricingRule
	isSet bool
}

func (v NullableCommonPricingRule) Get() *CommonPricingRule {
	return v.value
}

func (v *NullableCommonPricingRule) Set(val *CommonPricingRule) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonPricingRule) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonPricingRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonPricingRule(val *CommonPricingRule) *NullableCommonPricingRule {
	return &NullableCommonPricingRule{value: val, isSet: true}
}

func (v NullableCommonPricingRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonPricingRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


